# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django_apps.inventario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(editable=False, max_length=13, verbose_name='C\xf3digo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('p_compra', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Precio de Compra')),
                ('p_venta', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Precio de Venta')),
                ('avatar', models.ImageField(upload_to=django_apps.inventario.models.upload_location)),
            ],
            options={
                'ordering': ['-nombre'],
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Categor\xeda')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Categor\xedas',
            },
        ),
    ]
