# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_real', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Precio Real')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='IGV')),
                ('total', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Total')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.CompraEmpresa')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(editable=False, max_length=12, verbose_name='C\xf3digo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='carritoventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.OrdenVenta'),
        ),
    ]
