# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django_apps.persona.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('ap_pater', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('ap_mater', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=9, verbose_name='G\xe9nero')),
                ('domicilio', models.CharField(max_length=150, verbose_name='Domicilio')),
                ('telefono', models.CharField(max_length=9, verbose_name='Tel\xe9fono')),
                ('avatar', models.ImageField(upload_to=django_apps.persona.models.upload_location)),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('razon_social', models.CharField(max_length=150, verbose_name='Raz\xf3n Social')),
                ('ruc', models.CharField(max_length=11, verbose_name='RUC')),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(verbose_name='Descripci\xf3n')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direcci\xf3n')),
                ('contacto', models.CharField(max_length=150, verbose_name='Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electr\xf3nico')),
                ('avatar', models.ImageField(upload_to=django_apps.persona.models.upload_location)),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
